let user,store,products=[],orders=[];
const $=x=>document.getElementById(x);
async function boot(){let r=await sb.auth.getSession();user=r.data.session?.user;if(user)show();else $("app").hidden=true}
async function show(){$("loginBox").hidden=true;$("app").hidden=false;let r=await sb.from("stores").select("*").eq("owner_id",user.id).maybeSingle();store=r.data;if(!store){let x=await sb.from("stores").insert({owner_id:user.id,store_name:"RAFIQ STORE",mark:"R",whatsapp:"218926148563"}).select().single();store=x.data}fill();await loadProducts();await loadOrders();stats()}
function fill(){$("sName").value=store.store_name||"";$("sMark").value=store.mark||"R";$("sWa").value=store.whatsapp||"";$("sContact").value=store.contact||"";$("sHero").value=store.hero_title||"";$("sHeroText").value=store.hero_text||"";$("sOffer").value=store.offer_title||"";$("sOfferText").value=store.offer_text||""}
$("login").onclick=async()=>{let r=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});$("loginMsg").textContent=r.error?.message||"";if(!r.error)show()}
$("signup").onclick=async()=>{let r=await sb.auth.signUp({email:$("email").value,password:$("password").value});$("loginMsg").textContent=r.error?.message||"تم إنشاء الحساب. تحقق من البريد إن لزم."}
$("logout").onclick=async()=>{await sb.auth.signOut();location.reload()}
$("saveSettings").onclick=async()=>{let {error}=await sb.from("stores").update({store_name:$("sName").value,mark:$("sMark").value,whatsapp:$("sWa").value.replace(/\D/g,""),contact:$("sContact").value,hero_title:$("sHero").value,hero_text:$("sHeroText").value,offer_title:$("sOffer").value,offer_text:$("sOfferText").value}).eq("id",store.id);alert(error?.message||"تم الحفظ ✅");show()}
async function loadProducts(){let r=await sb.from("products").select("*").eq("owner_id",user.id).order("created_at",{ascending:false});products=r.data||[];$("productList").innerHTML=products.map(p=>`<div class="product"><img src="${p.image_url||""}"><div class="fields"><input id="n${p.id}" value="${p.name}"><input id="p${p.id}" type="number" value="${p.price}"><input id="o${p.id}" type="number" value="${p.old_price||""}"><input id="c${p.id}" value="${p.category||""}"><input id="b${p.id}" value="${p.badge||""}"><input id="i${p.id}" value="${p.image_url||""}"></div><button onclick="updateP(${p.id})">حفظ</button><button class="danger" onclick="delP(${p.id})">حذف</button></div>`).join("")}
$("newProduct").onclick=async()=>{await sb.from("products").insert({owner_id:user.id,name:"منتج جديد",price:0,category:"عام",active:true});loadProducts();stats()}
async function updateP(id){let {error}=await sb.from("products").update({name:$("n"+id).value,price:Number($("p"+id).value),old_price:Number($("o"+id).value)||null,category:$("c"+id).value,badge:$("b"+id).value,image_url:$("i"+id).value}).eq("id",id);alert(error?.message||"تم الحفظ ✅");loadProducts()}
async function delP(id){if(confirm("تحذف المنتج؟")){await sb.from("products").delete().eq("id",id);loadProducts();stats()}}
async function loadOrders(){let r=await sb.from("orders").select("*").eq("owner_id",user.id).order("created_at",{ascending:false});orders=r.data||[];$("ordersList").innerHTML=orders.map(o=>`<div class="order"><b>طلب #${o.id}</b><br>${o.customer_name||"بدون اسم"} • ${o.phone||""} • ${o.city||""}<br><strong>${o.total} د.ل</strong> • <select onchange="status(${o.id},this.value)"><option ${o.status=="new"?"selected":""}>new</option><option ${o.status=="processing"?"selected":""}>processing</option><option ${o.status=="done"?"selected":""}>done</option><option ${o.status=="cancelled"?"selected":""}>cancelled</option></select><details><summary>تفاصيل</summary><pre>${JSON.stringify(o.items,null,2)}</pre><p>${o.address||""}</p></details></div>`).join("")||"لا توجد طلبات."}
async function status(id,v){await sb.from("orders").update({status:v}).eq("id",id);loadOrders();stats()}
async function stats(){$("statProducts").textContent=products.length;$("statOrders").textContent=orders.length;$("statSales").textContent=orders.filter(o=>o.status!="cancelled").reduce((s,o)=>s+Number(o.total||0),0)+" د.ل";$("statNew").textContent=orders.filter(o=>o.status=="new").length}
$("refreshOrders").onclick=()=>{loadOrders().then(stats)};document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.hidden=true);$(b.dataset.tab).hidden=false;if(b.dataset.tab=="orders")loadOrders()});boot()
