-- RAFIQ STORE V5
create extension if not exists pgcrypto;
create table if not exists public.stores(
 id uuid primary key default gen_random_uuid(),
 owner_id uuid not null unique references auth.users(id) on delete cascade,
 store_name text not null default 'RAFIQ STORE', mark text default 'R',
 whatsapp text, contact text, hero_title text, hero_text text,
 offer_title text, offer_text text, created_at timestamptz default now()
);
create table if not exists public.products(
 id bigint generated by default as identity primary key,
 owner_id uuid not null references auth.users(id) on delete cascade,
 store_id uuid references public.stores(id) on delete cascade,
 name text not null, price numeric(12,2) not null default 0, old_price numeric(12,2),
 category text, badge text, image_url text, active boolean default true, created_at timestamptz default now()
);
create table if not exists public.orders(
 id bigint generated by default as identity primary key,
 owner_id uuid not null references auth.users(id) on delete cascade,
 store_id uuid references public.stores(id) on delete cascade,
 customer_name text, phone text, city text, address text,
 items jsonb not null default '[]', total numeric(12,2) not null default 0,
 status text not null default 'new', created_at timestamptz default now()
);
alter table public.stores enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;

create policy "store owner select" on public.stores for select using(auth.uid()=owner_id);
create policy "store owner insert" on public.stores for insert with check(auth.uid()=owner_id);
create policy "store owner update" on public.stores for update using(auth.uid()=owner_id);
create policy "products public active" on public.products for select using(active=true or auth.uid()=owner_id);
create policy "products owner insert" on public.products for insert with check(auth.uid()=owner_id);
create policy "products owner update" on public.products for update using(auth.uid()=owner_id);
create policy "products owner delete" on public.products for delete using(auth.uid()=owner_id);
create policy "orders owner read" on public.orders for select using(auth.uid()=owner_id);
create policy "orders owner insert" on public.orders for insert with check(auth.uid()=owner_id);
create policy "orders owner update" on public.orders for update using(auth.uid()=owner_id);

-- Ensure new products created by dashboard can be associated with the owner's store.
create or replace function public.set_product_store()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.store_id is null then select id into new.store_id from public.stores where owner_id=auth.uid(); end if;
  return new;
end $$;
drop trigger if exists products_store_trigger on public.products;
create trigger products_store_trigger before insert on public.products for each row execute function public.set_product_store();

-- Public storefront can insert orders only if they know the store id.
create policy "public order insert" on public.orders for insert with check(true);
