let cfg,products=[],cart=JSON.parse(localStorage.getItem("rv5-cart")||"[]"),cat="الكل";
const $=x=>document.getElementById(x);
async function init(){let s=await sb.from("stores").select("*").limit(1).maybeSingle();if(s.error)return err(s.error);cfg=s.data||{};$("name").textContent=cfg.store_name||"RAFIQ STORE";$("mark").textContent=cfg.mark||"R";$("foot").textContent=cfg.store_name||"RAFIQ STORE";$("contact").textContent=cfg.contact||"";$("heroTitle").innerHTML=cfg.hero_title||"تسوّق بسهولة.<br><em>اختار اللي يعجبك.</em>";$("heroText").textContent=cfg.hero_text||"";$("offerTitle").textContent=cfg.offer_title||"خصومات مميزة";$("offerText").textContent=cfg.offer_text||"";$("wa").href=wa("مرحباً، أريد الاستفسار");let p=await sb.from("products").select("*").eq("active",true).order("created_at",{ascending:false});if(p.error)return err(p.error);products=p.data||[];cats();render();$("count").textContent=cart.length}
function wa(t){return"https://wa.me/"+(cfg.whatsapp||"")+"?text="+encodeURIComponent(t)}
function cats(){let a=["الكل",...new Set(products.map(p=>p.category).filter(Boolean))];$("cats").innerHTML=a.map(x=>`<button class="${x==cat?"active":""}" onclick="cat='${x}';cats();render()">${x}</button>`).join("")}
function render(){let q=$("search").value.toLowerCase(),a=products.filter(p=>(cat=="الكل"||p.category==cat)&&p.name.toLowerCase().includes(q));$("grid").innerHTML=a.map(p=>`<article class="card"><div class="pic"><img src="${p.image_url||""}"><span>${p.badge||""}</span></div><small>${p.category||""}</small><h3>${p.name}</h3><b>${p.price} د.ل</b> ${p.old_price?`<del>${p.old_price} د.ل</del>`:""}<button class="add" onclick="add(${p.id})">أضف للسلة</button></article>`).join("")||"<p>مافيش نتائج.</p>"}
function add(id){cart.push(id);localStorage.setItem("rv5-cart",JSON.stringify(cart));$("count").textContent=cart.length;drawer()}
function drawer(){$("drawer").classList.add("show");$("overlay").classList.add("show");let p=cart.map(id=>products.find(x=>x.id==id)).filter(Boolean);$("items").innerHTML=p.map(x=>`<div class="line"><img src="${x.image_url}"><span>${x.name}<br>${x.price} د.ل</span><button onclick="removeItem(${x.id})">×</button></div>`).join("")||"<p>السلة فارغة.</p>";let total=p.reduce((s,x)=>s+x.price,0);$("total").innerHTML=p.length?`<b>المجموع: ${total} د.ل</b><button class="primary" onclick="checkout()">إتمام الطلب</button>`:""}
function removeItem(id){cart.splice(cart.indexOf(id),1);localStorage.setItem("rv5-cart",JSON.stringify(cart));$("count").textContent=cart.length;drawer()}
async function checkout(){let p=cart.map(id=>products.find(x=>x.id==id)).filter(Boolean),total=p.reduce((s,x)=>s+x.price,0),name=prompt("اسمك؟"),phone=prompt("رقم الهاتف؟"),city=prompt("المدينة؟"),address=prompt("العنوان؟");if(!name||!phone)return;let {error}=await sb.from("orders").insert({store_id:cfg.id,customer_name:name,phone,city,address,items:p.map(x=>({id:x.id,name:x.name,price:x.price})),total,status:"new"});if(error)return alert("تعذر حفظ الطلب: "+error.message);let lines=p.map(x=>`- ${x.name} — ${x.price} د.ل`).join("\n");location.href=wa(`طلب جديد من ${name}\n${lines}\nالمجموع: ${total} د.ل\nالهاتف: ${phone}\nالمدينة: ${city}\nالعنوان: ${address}`)}
function err(e){console.error(e);$("grid").innerHTML="<p>تحقق من إعداد Supabase وملف config.js.</p>"}
$("search").oninput=render;$("cartBtn").onclick=drawer;$("close").onclick=()=>{$("drawer").classList.remove("show");$("overlay").classList.remove("show")};$("overlay").onclick=$("close").onclick;$("theme").onclick=()=>document.body.classList.toggle("dark");init()
